services:
  - type: web
    name: smart-attendance-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
